name: Read Hello.txt file

on: 
  push:
    branches:
      - main

jobs:
  read_the_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read Hello.txt file
        run: |
          ls -l
          echo "Content of Hello.txt: \n"
          cat Hello.txt
